#!/usr/bin/env node
/**
 * Regenerate src/pricing-data.ts from LiteLLM's model_prices_and_context_window.json.
 * Keeps only chat models from providers that coding agents use, and only the four
 * per-token rates tokseal prices with, converted to USD per million tokens.
 *   npm run sync-pricing -w @tokseal/core
 */
import { writeFileSync } from 'node:fs';

const SRC = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';
const PROVIDERS = new Set(['anthropic', 'openai', 'gemini', 'vertex_ai-language-models', 'vertex_ai-anthropic_models', 'bedrock', 'bedrock_converse', 'azure', 'xai', 'deepseek', 'mistral', 'groq', 'openrouter', 'dashscope', 'moonshot', 'minimax', 'zai', 'github_copilot', 'ollama']);
const KEEP_PREFIX = /^(claude|gpt|o[1-9]|codex|gemini|qwen|deepseek|grok|mistral|codestral|kimi|glm|minimax|llama|mimo)/i;

const res = await fetch(SRC);
if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
const all = await res.json();
const out = {};
const perM = (v) => (typeof v === 'number' && Number.isFinite(v) && v >= 0 ? Math.round(v * 1e6 * 1e6) / 1e6 : undefined);

// Un-prefixed keys ("gpt-5") are canonical; prefixed variants ("azure/gpt-5") only fill gaps.
const entries = Object.entries(all).sort(([a], [b]) => Number(a.includes('/')) - Number(b.includes('/')));
for (const [rawKey, m] of entries) {
  if (!m || typeof m !== 'object' || (m.mode && m.mode !== 'chat' && m.mode !== 'responses')) continue;
  const provider = m.litellm_provider ?? '';
  const key = rawKey.toLowerCase().replace(/^[a-z0-9_.-]+\//, ''); // strip "provider/" prefix
  if (!PROVIDERS.has(provider) && !KEEP_PREFIX.test(key)) continue;
  if (!KEEP_PREFIX.test(key)) continue;
  const input = perM(m.input_cost_per_token), output = perM(m.output_cost_per_token);
  if (input === undefined || output === undefined) continue;
  const row = { input, output, cacheRead: perM(m.cache_read_input_token_cost) ?? 0, cacheWrite: perM(m.cache_creation_input_token_cost) ?? 0 };
  // Prefer the un-prefixed key; the first provider seen wins, later duplicates are ignored.
  if (!(key in out)) out[key] = row;
}

const keys = Object.keys(out).sort();
const lines = keys.map((k) => `  ${JSON.stringify(k)}: { input: ${out[k].input}, output: ${out[k].output}, cacheRead: ${out[k].cacheRead}, cacheWrite: ${out[k].cacheWrite} },`);
const ts = `// GENERATED by scripts/sync-pricing.mjs from LiteLLM — do not edit by hand.
// Source: ${SRC}
// Synced: ${new Date().toISOString().slice(0, 10)} · ${keys.length} models · USD per 1,000,000 tokens
import type { PricePerMillion } from './pricing.js';

export const LITELLM_PRICES: Record<string, PricePerMillion> = {
${lines.join('\n')}
};
`;
writeFileSync(new URL('../src/pricing-data.ts', import.meta.url), ts);
console.log(`wrote ${keys.length} models to src/pricing-data.ts`);
